service: invisible_wins

image: ghcr.io/taylor01/visible_wins

servers:
  web:
    - 192.81.209.97

proxy:
  ssl: true
  host: www.invisiblewins.com  # Use just one domain that points to your server

registry:
  server: ghcr.io
  username: taylor01
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - OKTA_CLIENT_SECRET
    - KAMAL_REGISTRY_PASSWORD
    - OKTA_CLIENT_ID
    - OKTA_ISSUER_URL
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_LOG_TO_STDOUT: "true"
    RAILS_SERVE_STATIC_FILES: "true"

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "visible_wins_storage:/rails/storage"
  - "db:/rails/db"

asset_path: /rails/public/assets

builder:
  arch: amd64
